[bits 64]
default rel

section .text
global user_syscall_entry
global syscall_init_asm

extern syscall_dispatch
extern process_exit
extern serial_print
extern serial_print_hex

; ---------------------------------------------------------------------------
; Syscall init: set up EFER, STAR, LSTAR, FMASK
; ---------------------------------------------------------------------------
syscall_init_asm:
    ; Enable SYSCALL/SYSRET in EFER
    mov ecx, 0xC0000080
    rdmsr
    or eax, 0x1
    wrmsr

    ; Set up STAR (User CS = 0x30 -> STAR[15:0] = 0x20)
    ; In DonsDOS privilege maps: Kernel CS=0x18, User CS=0x30 (STAR[15:0]=0x20)
    mov ecx, 0xC0000081
    xor edx, edx
    xor eax, eax
    mov edx, 0x00180000
    mov eax, 0x00200000
    wrmsr

    ; Set up LSTAR (Long Mode System Call Target Address)
    mov ecx, 0xC0000082
    mov rax, user_syscall_entry
    wrmsr

    ; Set up FMASK (Clear Interrupt Flag on syscall entry for atomic transitions)
    mov ecx, 0xC0000084
    mov eax, 0x00000200    ; Clear IF (bit 9) to temporarily mask interrupts
    xor edx, edx
    wrmsr

    ret
; ---------------------------------------------------------------------------
; Syscall entry from usermode
; ---------------------------------------------------------------------------
user_syscall_entry:
    ; On raw execution entry:
    ; RCX = Userland RIP (saved by CPU)
    ; R11 = Userland RFLAGS (saved by CPU)
    ; RAX = System Call Identifier Number
    
    ; 1. PRESERVE RETURN CONTEXT IMMEDIATELY:
    ; Copy volatile registers containing user return vectors into safe,
    ; non-clobbered registers (R12 and R13) before translating arguments.
    mov r12, rcx                    ; r12 = Saved Userland RIP
    mov r13, r11                    ; r13 = Saved Userland RFLAGS

    push rsp                        ; Store Userland RSP onto the call stack matrix
    push rbp                        ; Store Userland RBP
    push r12                        ; Store Userland RIP safely
    push r13                        ; Store Userland RFLAGS safely

    ; 2. Preserve all standard System V non-volatile registers
    push rbx
    push r12
    push r13
    push r14
    push r15

    ; 3. Preserve volatile registers R8 and R9 from compiler modifications
    push r8
    push r9

    ; 4. System Call Argument Layout Translation Pass:
    ; Userland registers passed: rax=num, rdi=arg0, rsi=arg1, rdx=arg2, r10=arg3, r8=arg4, r9=arg5
    ; C signature expects: syscall_dispatch(num, arg0, arg1, arg2, arg3, arg4, arg5)
    ; System V ABI expects:   rdi,  rsi,  rdx,  rcx,  r8,   r9,   [stack]
    
    push r9                         ; Parameter 7 (arg5) -> Placed on the stack frame
    mov r9, r8                      ; Parameter 6 (arg4) -> Moves into r9
    mov r8, r10                     ; Parameter 5 (arg3) -> Moves into r8
    mov rcx, rdx                    ; Parameter 4 (arg2) -> Moves safely into rcx
    mov rdx, rsi                    ; Parameter 3 (arg1) -> Moves into rdx
    mov rsi, rdi                    ; Parameter 2 (arg0) -> Moves into rsi
    mov rdi, rax                    ; Parameter 1 (num)  -> Moves into rdi

    call syscall_dispatch
    add rsp, 8                      ; Instantly discard stacked Parameter 7

    ; Check if process called SYS_EXIT (2)
    cmp rdi, 2                      ; rdi contains our tracked syscall number (num)
    je .handle_exit

    ; 5. Restore registers back to their original userland states
    pop r9
    pop r8
    
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbx
    
    ; PATCH: Explicitly retain RAX (the return value from syscall_dispatch)
    ; By skipping a manual POP RAX or overwrite here, RAX holds the exact
    ; character count or error metrics generated by the C handlers.
    
    pop r11                         ; Restore Userland CPU Flags (RFLAGS)
    pop rcx                         ; Restore Userland Instruction Pointer (RIP)
    pop rbp
    pop rsp                         ; Restore Userland Stack Pointer (RSP)
    
    o64 sysret                      ; Secure privilege step down to Ring 3

.handle_exit:
    pop r9
    pop r8
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbx
    add rsp, 16                     ; Discard saved flags and instruction pointers
    pop rbp
    add rsp, 8                      ; Discard saved userland RSP
    
    push rax                        ; Preserve exit status value
    mov rdi, exit_msg
    call serial_print
    pop rax
    push rax
    call serial_print_hex
    mov rdi, newline
    call serial_print
    pop rax
    
    mov rdi, rax                    ; Forward exit status to cleanup routine
    jmp process_exit                ; Control branch handover (never returns)

section .data
exit_msg: db "SYS_EXIT: status=", 0
newline: db 0x0A, 0x0D, 0
